// Data luu vao local

var productArray = [{
        id: 1,
        name: "Dolce Gabbana The Only One For Women EDP 50ml",
        brand: "Dolce Gabbana",
        type: "Nữ",
        price: 1800000,
        img1: "[id 1]Nuoc Hoa Nu Dolce Gabbana The Only One For Women EDP 50ml  (1).jpg",
        img2: "[id 1]Nuoc Hoa Nu Dolce Gabbana The Only One For Women EDP 50ml  (2).jpg",
        img3: "[id 1]Nuoc Hoa Nu Dolce Gabbana The Only One For Women EDP 50ml  (1).jpg",
        xuat_xu: "Pháp, Anh, Đức",
        nam_phat_hanh: "2018",
        nhom_huong: "Hương caramel, Trái lê, Hoa diên vỹ, Vanilla",
        phong_cach: "Ngọt ngào, Sexy, Gợi cảm, Hiện đại",
        huong_dau: "Hoa Violet, Quả cam, Cam Bergamot",
        huong_giua: "Quả lê, Cà phê, Diên vĩ, Hoa cam, Hoa hồng",
        huong_cuoi: "Caramel, Vanilla, Hoắc hươn"
    },

    {
        id: 2,
        name: "Chanel Coco Mademoiselle Intense 100ml",
        brand: "Chanel",
        type: "Nữ",
        price: 3550000,
        img1: "[id 2]Nuoc Hoa Cho Nu Chanel Coco Mademoiselle Intense, 100ml (1).jpg",
        img2: "[id 2]Nuoc Hoa Cho Nu Chanel Coco Mademoiselle Intense, 100ml (2).jpg",
        img3: "[id 2]Nuoc Hoa Cho Nu Chanel Coco Mademoiselle Intense, 100ml (3).jpg",
        xuat_xu: "Pháp",
        nam_phat_hanh: "2018",
        nhom_huong: "Hoắc hương, Đậu tonka, Vani madagascar, Quả cam sicili",
        phong_cach: "Nữ tính, Gợi cảm, Sang trọng",
        huong_dau: "Quả cam Sicili, Cam Bergamot Calabria",
        huong_giua: "Hoa hồng, Hoa nhài, Hương trái cây",
        huong_cuoi: "Cây hoắc hương, Đậu Tonka, Hương Vani Madagascar"
    },

    {
        id: 3,
        name: "Dior Miss Dior Rose N’roses EDT 100ml",
        brand: "Christian Dior",
        type: "Nữ",
        price: 2790000,
        img1: "[id 3]Nuoc Hoa Nu Dior Miss Dior Rose N’roses EDT 100ml (1).jpg",
        img2: "[id 3]Nuoc Hoa Nu Dior Miss Dior Rose N’roses EDT 100ml (2).jpg",
        img3: "[id 3]Nuoc Hoa Nu Dior Miss Dior Rose N’roses EDT 100ml (3).jpg",
        xuat_xu: "Pháp",
        nam_phat_hanh: "2020",
        nhom_huong: "Hoa hồng, Xạ hương, Hoa phong lữ",
        phong_cach: "Ngọt ngào, Gợi cảm, Mãnh liệt",
        huong_dau: "Hoa phong lữ, Cam Bergamot, Quả quýt Ý",
        huong_giua: "Hoa hồng Grasse, Hoa hồng Damask",
        huong_cuoi: "Xạ hương"
    },

    {
        id: 4,
        name: "Gucci Flora Gorgeous Gardenia EDP 100ml",
        brand: "Gucci",
        type: "Nữ",
        price: 2500000,
        img1: "[id 4]Nuoc Hoa Nu Gucci Flora Gorgeous Gardenia EDP 100ml  (1).jpg",
        img2: "[id 4]Nuoc Hoa Nu Gucci Flora Gorgeous Gardenia EDP 100ml  (2).jpg",
        img3: "[id 4]Nuoc Hoa Nu Gucci Flora Gorgeous Gardenia EDP 100ml  (3).jpg",
        xuat_xu: "Anh, Đức, Pháp",
        nam_phat_hanh: "2021",
        nhom_huong: "Hoa lê, Đường nâu, Hoa nhài",
        phong_cach: "Hoa hồng, Xạ hương, Hoa phong lữ",
        huong_dau: "Hoa Lê",
        huong_giua: "Hoa Nhài, Cây Dành Dành",
        huong_cuoi: "Đường Nâu, Hoắc Hương"
    },

    {
        id: 5,
        name: "Calvin Klein (CK) Euphoria For Women EDP 100ml",
        brand: "Calvin Klein",
        type: "Nữ",
        price: 1300000,
        img1: "[id 5]Nuoc Hoa Nu Calvin Klein (CK) Euphoria For Women EDP Goi Cam, 100ml  (1).jpg",
        img2: "[id 5]Nuoc Hoa Nu Calvin Klein (CK) Euphoria For Women EDP Goi Cam, 100ml  (2).jpg",
        img3: "[id 5]Nuoc Hoa Nu Calvin Klein (CK) Euphoria For Women EDP Goi Cam, 100ml  (3).jpg",
        xuat_xu: "Mỹ, Pháp",
        nam_phat_hanh: "2005",
        nhom_huong: "Quả lựu, Hoa lan, Gỗ mahogany, Hổ phách, Xạ hương",
        phong_cach: "Quyến rũ, Tươi mới, Tự do",
        huong_dau: "Quả lựu",
        huong_giua: "Hoa sen, Hoa phong lan",
        huong_cuoi: "Hoa tím, Hổ phách, Xạ hương, Gỗ gụ"
    },

    {
        id: 6,
        name: "Prada L'Homme Intense EDP 100ml",
        brand: "Prada",
        type: "Nam",
        price: 1980000,
        img1: "[id 6]Nuoc Hoa Nam Prada L'Homme Intense EDP 100ml  (1).jpg",
        img2: "[id 6]Nuoc Hoa Nam Prada L'Homme Intense EDP 100ml  (2).jpg",
        img3: "[id 6]Nuoc Hoa Nam Prada L'Homme Intense EDP 100ml  (3).jpg",
        xuat_xu: "Pháp, Tây Ban Nha",
        nam_phat_hanh: "2017",
        nhom_huong: "Hoa diên vĩ, Đậu tonka, Da thuộc",
        phong_cach: "Nam tính, Tự tin, Hiện đại, Cuốn hút",
        huong_dau: "Hoa Diên Vĩ",
        huong_giua: "Quảng Hoắc Hương, Hổ Phách",
        huong_cuoi: "Da Thuộc, Đậu Tonka, Gỗ Đàn Hương"
    },

    {
        id: 7,
        name: "Creed Aventus For Men EDP 100ml",
        brand: "Creed",
        type: "Nam",
        price: 6750000,
        img1: "[id 7]Nuoc Hoa Nam Creed Aventus For Men EDP 100ml (1).jpg",
        img2: "[id 7]Nuoc Hoa Nam Creed Aventus For Men EDP 100ml (2).jpg",
        img3: "[id 7]Nuoc Hoa Nam Creed Aventus For Men EDP 100ml (3).jpg",
        xuat_xu: "Pháp",
        nam_phat_hanh: "2010",
        nhom_huong: "Dứa, Gỗ bu-lo, Xạ hương, Quả lý chua đen",
        phong_cach: "Quyền lực, Nam tính, Hấp dẫn, Tinh tế",
        huong_dau: "Dứa, Cam Bergamot, Lý Chua Đen, Táo",
        huong_giua: "Bạch Dương. Hoắc Hương, Hoa Nhài, Hồng",
        huong_cuoi: "Xạ Hương, Rêu Sồi, Ambergris, Vanilla"
    },

    {
        id: 8,
        name: "Bvlgari Man In Black For Men, 100ml",
        brand: "Bvlgari",
        type: "Nam",
        price: "2200000",
        img1: "[id 8]Nuoc Hoa Bvlgari Man In Black For Men, 100ml  (1).jpg",
        img2: "[id 8]Nuoc Hoa Bvlgari Man In Black For Men, 100ml  (2).jpg",
        img3: "[id 8]Nuoc Hoa Bvlgari Man In Black For Men, 100ml  (3).jpg",
        xuat_xu: "Ý",
        nam_phat_hanh: "2014",
        nhom_huong: "Gia vị, Rượu rum, Da thuộc",
        phong_cach: "Nam tính, Ấm áp, Lịch lãm",
        huong_dau: "Cây thuốc lá, Rượu Rum, Gia vị",
        huong_giua: "Da thuộc, Hoa huệ trắng, Hoa diên vĩ",
        huong_cuoi: "Gỗ Guaiac, An tức hương, Đậu Tonka"
    },

    {
        id: 9,
        name: "Ralph Lauren Polo Blue EDP 125ml",
        brand: "Ralph Lauren",
        type: "Nam",
        price: 1950000,
        img1: "[id 9]Nuoc Hoa Ralph Lauren Polo Blue EDP Cho Nam 125ml (1).jpg",
        img2: "[id 9]Nuoc Hoa Ralph Lauren Polo Blue EDP Cho Nam 125ml (2).jpg",
        img3: "[id 9]Nuoc Hoa Ralph Lauren Polo Blue EDP Cho Nam 125ml (3).jpg",
        xuat_xu: "Mỹ",
        nam_phat_hanh: "2016",
        nhom_huong: "Hương biển, Da lộn, Cam bergamot, Cỏ hương bài",
        phong_cach: "Mạnh mẽ, Nam tính, Hấp dẫn",
        huong_dau: "Hương biển, Cam bergamot, Bạch đậu khấu",
        huong_giua: "Húng quế, Cỏ roi ngựa, Xô thơm, Rễ cây diên vĩ",
        huong_cuoi: "Da lộn, Cỏ hương bài, Hương gỗ, Hoắc hương"
    },

    {
        id: 10,
        name: "Versace Man Eau Fraiche 100ml",
        brand: "Versace",
        type: "Nam",
        price: 1350000,
        img1: "[id 10]Nuoc Hoa Nam Versace Man Eau Fraiche 100ml  (1).jpg",
        img2: "[id 10]Nuoc Hoa Nam Versace Man Eau Fraiche 100ml  (2).jpg",
        img3: "[id 10]Nuoc Hoa Nam Versace Man Eau Fraiche 100ml  (3).jpg",
        xuat_xu: "Ý",
        nam_phat_hanh: "2006",
        nhom_huong: "Quả chanh vàng, Cam bergamot, Quả khế, Gỗ tuyết tùng",
        phong_cach: "Tươi mát, Nam tính, Tự tin",
        huong_dau: "Cam Bergamot, Gỗ cẩm lai Brazil, Bạch đậu khấu, Chanh vàng, Quả khế",
        huong_giua: "Cây ngải giấm, Cây xô thơm, Gỗ tuyết tùng, Tiêu",
        huong_cuoi: "Hổ phách, Nghệ tây, Xạ hương, Hương của gỗ, Cây sung dâu"
    },

    {
        id: 11,
        name: "Versace Bright Crystal Absolu EDP 90ml",
        brand: "Versace",
        type: "Nữ",
        price: 1680000,
        img1: "[id 11]Nuoc Hoa Nu Versace Bright Crystal Absolu EDP, 90ml (1).jpg",
        img2: "[id 11]Nuoc Hoa Nu Versace Bright Crystal Absolu EDP, 90ml (2).jpg",
        img3: "[id 11]Nuoc Hoa Nu Versace Bright Crystal Absolu EDP, 90ml (3).jpg",
        xuat_xu: "Ý",
        nam_phat_hanh: "2013",
        nhom_huong: "Hoa mãu đơn, Phúc bồn tử, Quả lựu, Cam yuzu, Hoa sen",
        phong_cach: "Nữ Tính, Hiện Đại, Gợi Cảm",
        huong_dau: "Quả Yuzu, Lựu, Hương nước",
        huong_giua: "Hoa sen, Hoa mẫu đơn, Mâm xôi, Hoa Mộc lan",
        huong_cuoi: "Hổ phách, Xạ hương, Gỗ gụ"
    },

    {
        id: 12,
        name: "Ralph Lauren Polo Black EDT 125ml",
        brand: "Ralph Lauren",
        type: "Nam",
        price: 1749000,
        img1: "[id 12]Nước Hoa Nam Ralph Lauren Polo Black EDT 125ml (1).jpg",
        img2: "[id 12]Nước Hoa Nam Ralph Lauren Polo Black EDT 125ml (2).jpg",
        img3: "[id 12]Nước Hoa Nam Ralph Lauren Polo Black EDT 125ml (3).jpg",
        xuat_xu: "Mỹ",
        nam_phat_hanh: "2005",
        nhom_huong: "Quả xoài, Gỗ đàn hương, Qủa quýt, Hoắc hương",
        phong_cach: "Nam tính, Lịch lãm, Thu hút",
        huong_dau: "Xoài, Gỗ Đàn Hương, Quả Quýt",
        huong_giua: "Cây Hoắc Hương, Đậu Tonka, Cây Ngải Cứu",
        huong_cuoi: "Cây Xô Thơm, Quả Chanh"
    },

    {
        id: 13,
        name: "Bvlgari Omnia Golden Citrine EDT 65ml",
        brand: "Bvlgari",
        type: "Nữ",
        price: 1600000,
        img1: "[id 13]Nuoc Hoa Nu Bvlgari Omnia Golden Citrine EDT 65ml (1).jpg",
        img2: "[id 13]Nuoc Hoa Nu Bvlgari Omnia Golden Citrine EDT 65ml (2).jpg",
        img3: "[id 13]Nuoc Hoa Nu Bvlgari Omnia Golden Citrine EDT 65ml (3).jpg",
        xuat_xu: "Ý",
        nam_phat_hanh: "2020",
        nhom_huong: "Hoa hoàng lan, An tức hương, Quả cam",
        phong_cach: "Tính tế, Nữ tính, Hiện đại",
        huong_dau: "Quả Quýt Sicilian, Quả Đào Trắng",
        huong_giua: "Ylang-Ylang, Hoa Nhài",
        huong_cuoi: "Benzoin, Chi Tuyết Tùng"
    },

    {
        id: 14,
        name: "Unisex Creed Millesime Imperial EDP 100ml",
        brand: "Creed",
        type: "unisex",
        price: 5580000,
        img1: "[id 14]Nuoc Hoa Unisex Creed Millesime Imperial EDP 100ml (1).jpg",
        img2: "[id 14]Nuoc Hoa Unisex Creed Millesime Imperial EDP 100ml (2).jpg",
        img3: "[id 14]Nuoc Hoa Unisex Creed Millesime Imperial EDP 100ml (3).jpg",
        xuat_xu: "Pháp",
        nam_phat_hanh: "1995",
        nhom_huong: "Hương trái cây, Muối biển, Hương biển, Xạ hương",
        phong_cach: "Sang trọng, Gợi cảm, Tinh tế",
        huong_dau: "Trái cây, Muối biển",
        huong_giua: "Hoa diên vĩ, Quýt hồng, Chanh, Cam bergamot",
        huong_cuoi: "Xạ hương, Hương gỗ, Hương biển"
    },

    {
        id: 15,
        name: "Prada Candy Eau De Parfum 80ml",
        brand: "Prada",
        type: "Nữ",
        price: 2500000,
        img1: "[id 15]Nuoc Hoa Nu Prada Candy Eau De Parfum 80ml (1).jpg",
        img2: "[id 15]Nuoc Hoa Nu Prada Candy Eau De Parfum 80ml (2).jpg",
        img3: "[id 15]Nuoc Hoa Nu Prada Candy Eau De Parfum 80ml (3).jpg",
        xuat_xu: "Pháp, Tây Ban Nha",
        nam_phat_hanh: "2011",
        nhom_huong: "Hương caramen, Hương benzoin, Xạ hương, Hương phấn",
        phong_cach: "Sang trọng, Gợi cảm, Nữ tính",
        huong_dau: "Caramel",
        huong_giua: "Hương Phấn, Xạ Hương",
        huong_cuoi: "Benzoin, Vani"
    },

    {
        id: 16,
        name: "Calvin Klein Euphoria EDT 100ml",
        brand: "Calvin Klein",
        type: "Nam",
        price: 1150000,
        img1: "[id 16]Nuoc Hoa Nam Calvin Klein Euphoria For Men EDT 100ml (1).jpg",
        img2: "[id 16]Nuoc Hoa Nam Calvin Klein Euphoria For Men EDT 100ml (2).jpg",
        img3: "[id 16]Nuoc Hoa Nam Calvin Klein Euphoria For Men EDT 100ml (3).jpg",
        xuat_xu: "Mỹ",
        nam_phat_hanh: "2005",
        nhom_huong: "Woody Aromatic:Hương gỗ thơm,thảo mộc",
        phong_cach: "Mạnh mẽ,nam tính,sang trọng",
        huong_dau: "Gừng, Tiêu",
        huong_giua: "Cây húng quế đen, Cây xô thơm, Gỗ tuyết tùng",
        huong_cuoi: "Hổ phách, Cây hoắc hương, Gỗ gụ, Da lộn"
    },

    {
        id: 17,
        name: "Gucci Guilty Pour Homme EDP 90ml",
        brand: "Gucci",
        type: "Nam",
        price: 1150000,
        img1: "[id 17]Nuoc Hoa Nam Gucci Guilty Pour Homme EDP 90ml (1).jpg",
        img2: "[id 17]Nuoc Hoa Nam Gucci Guilty Pour Homme EDP 90ml (2).jpg",
        img3: "[id 17]Nuoc Hoa Nam Gucci Guilty Pour Homme EDP 90ml (13).jpg",
        xuat_xu: "Anh, Đức, Pháp",
        nam_phat_hanh: "2020",
        nhom_huong: "Giấm balsamic, Hoa hồng, Hoa cam",
        phong_cach: "Tinh tế, Nam tính, Thu hút",
        huong_dau: "Hoa Hồng Tươi, Tiêu, Tiêu Đỏ, Giấm balsamic",
        huong_giua: "Orange Blossom, Hoa Cam, Hoa Oải Hương",
        huong_cuoi: "Hoắc Hương, Tuyết Tùng"
    },

    {
        id: 18,
        name: "Dior Homme Ban 2020 EDP Intense 100ml",
        brand: "Dior",
        type: "Nam",
        price: 2620000,
        img1: "[id 18]Nuoc Hoa Nam Dior Homme Ban 2020 EDP Intense 100ml (1).jpg",
        img2: "[id 18]Nuoc Hoa Nam Dior Homme Ban 2020 EDP Intense 100ml (2).jpg",
        img3: "[id 18]Nuoc Hoa Nam Dior Homme Ban 2020 EDP Intense 100ml (3).jpg",
        xuat_xu: "Pháp",
        nam_phat_hanh: "2011",
        nhom_huong: "Hương gỗ hoa ,cỏ xạ hương, Hoa diên vĩ, Cây vông vang",
        phong_cach: "Lịch lãm , Quyến rũ, Thu hút",
        huong_dau: "Hoa Oải Hương (Lavender)",
        huong_giua: "Hoa diên vĩ, Cây vông vang, Quả lê",
        huong_cuoi: "Cỏ hương bài, Gỗ tuyết tùng Virginia"
    },

    {
        id: 19,
        name: "Chanel Bleu De Chanel EDP 100ml",
        brand: "Chanel",
        type: "Nam",
        price: 3250000,
        img1: "[id 19]Nuoc Hoa Nam Chanel Bleu De Chanel EDP, 100ml (1).jpg",
        img2: "[id 19]Nuoc Hoa Nam Chanel Bleu De Chanel EDP, 100ml (2).jpg",
        img3: "[id 19]Nuoc Hoa Nam Chanel Bleu De Chanel EDP, 100ml (1).jpg",
        xuat_xu: "Pháp",
        nam_phat_hanh: "2011",
        nhom_huong: "Hương gỗ hoa ,cỏ xạ hương, Hoa diên vĩ, Cây vông vang",
        phong_cach: "Gợi cảm, Sang Trọng, Tinh tế, Lịch lãm",
        huong_dau: "Chanh vàng, Ớt hồng, Bạc hà",
        huong_giua: "Dưa vàng, Hoa nhài, Gừng",
        huong_cuoi: "Gỗ tuyết tùng, Hổ phách, Gỗ đàn hương"
    },

    {
        id: 20,
        name: "Dolce & Gabbana The Only One 2 EDP 100ml",
        brand: "Dolce Gabbana",
        type: "Nữ",
        price: 2500000,
        img1: "[id 20]Nuoc Hoa Nu Dolce & Gabbana The Only One 2 EDP 100ml (1).jpg",
        img2: "[id 20]Nuoc Hoa Nu Dolce & Gabbana The Only One 2 EDP 100ml (2).jpg",
        img3: "[id 20]Nuoc Hoa Nu Dolce & Gabbana The Only One 2 EDP 100ml (3).jpg",
        xuat_xu: "Anh, Đức, Pháp",
        nam_phat_hanh: "2019",
        nhom_huong: "Qủa mâm xôi, Qủa mọng, Đậu tonka",
        phong_cach: "Tinh tế, Gợi cảm, Khiêu khích",
        huong_dau: "Quả lê, Quả mọng đỏ, Quả mâm xôi, Hoa lan Nam Phi",
        huong_giua: "Hoa hồng đỏ, Hoa tím, Cà phê",
        huong_cuoi: "Đậu tonka, Hoắc hương, Long diên hương, Hổ phách"
    },

    {
        id: 21,
        name: "Dolce & Gabbana (D&G) The One EDP 100ml",
        brand: "Dolce Gabbana",
        type: "Nam",
        price: 1890000,
        img1: "[id 21]Nuoc Hoa Dolce & Gabbana (D&G) The One Danh Cho Nam Gioi EDP, 100ml (1).jpg",
        img2: "[id 21]Nuoc Hoa Dolce & Gabbana (D&G) The One Danh Cho Nam Gioi EDP, 100ml (2).jpg",
        img3: "[id 21]Nuoc Hoa Dolce & Gabbana (D&G) The One Danh Cho Nam Gioi EDP, 100ml (1).jpg",
        xuat_xu: "Anh, Đức, Pháp",
        nam_phat_hanh: "2015",
        nhom_huong: "Hổ phách, Thuốc lá, Gừng, Bạch đậu khấu",
        phong_cach: "Quyến rũ, Nam tính, Lịch lãm",
        huong_dau: "Bưởi, Húng quế, Rau mùi ",
        huong_giua: "Gừng, Bạch đậu khấu, Hoa cam ",
        huong_cuoi: "Thuốc lá, Hổ phách, Gỗ tuyết tùng "
    },

    {
        id: 22,
        name: "Chanel Allure Homme Sport EDT 100ml",
        brand: "Chanel",
        type: "Nam",
        price: 2760000,
        img1: "[id 22]Nuoc Hoa Nam Chanel Allure Homme Sport EDT, 100ml (1).jpg",
        img2: "[id 22]Nuoc Hoa Nam Chanel Allure Homme Sport EDT, 100ml (2).jpg",
        img3: "[id 22]Nuoc Hoa Nam Chanel Allure Homme Sport EDT, 100ml (3).jpg",
        xuat_xu: "Pháp",
        nam_phat_hanh: "2004",
        nhom_huong: "Cam đỏ, Hương biển, An-đê-hít",
        phong_cach: "Tinh tế, Nam tính, Tươi mát, Hiện đại",
        huong_dau: "Hương An-đê-hít, Quả cam, Hương nước biển",
        huong_giua: "Tiêu, Hoa cam Neroli, Gỗ tuyết tùng",
        huong_cuoi: "Đậu Tonka, Hổ phách, Hương Va ni, Xạ hương trắng"
    },

    {
        id: 23,
        name: "Miss Dior Absolutely Blooming 100ml",
        brand: "Dior",
        type: "Nữ",
        price: 2880000,
        img1: "[id 23]Nuoc Hoa Miss Dior Absolutely Blooming 100ml (1).jpg",
        img2: "[id 23]Nuoc Hoa Miss Dior Absolutely Blooming 100ml (2).jpg",
        img3: "[id 23]Nuoc Hoa Miss Dior Absolutely Blooming 100ml (3).jpg",
        xuat_xu: "Pháp",
        nam_phat_hanh: "2016",
        nhom_huong: "Hoa lê, Đường nâu, Hoa nhà",
        phong_cach: "Nữ tính, Hiện đại, Ngọt ngào",
        huong_dau: "Quả mâm xôi, Quả lựu, Quả lý chua đen, Hạt tiêu hồng",
        huong_giua: "Hoa hồng tháng năm, Hoa mẫu đơn",
        huong_cuoi: "Xạ hương trắng"
    },

    {
        id: 24,
        name: "Gucci Bloom EDP For Women 100ml",
        brand: "Gucci",
        type: "Nữ",
        price: 2900000,
        img1: "[id 24]Nuoc Hoa Nu Gucci Bloom EDP For Women 100ml (1).jpg",
        img2: "[id 24]Nuoc Hoa Nu Gucci Bloom EDP For Women 100ml (2).jpg",
        img3: "[id 24]Nuoc Hoa Nu Gucci Bloom EDP For Women 100ml (3).jpg",
        xuat_xu: "Anh, Đức, Pháp",
        nam_phat_hanh: "2017",
        nhom_huong: "Hoa huệ, Hoa nhài, Hoa kim ngân",
        phong_cach: "Quyến rũ, Sang trọng, Quý phái",
        huong_dau: "Hoa nhài",
        huong_giua: "Hoa huệ",
        huong_cuoi: "Hoa sử quân tử"
    },

    {
        id: 25,
        name: "Calvin Klein Beauty Eau De Parfum For Her 100ml",
        brand: "Calvin Klein",
        type: "Nữ",
        price: 1200000,
        img1: "[id 25]Nuoc Hoa Calvin Klein Beauty Eau De Parfum For Her 100ml (1).jpg",
        img2: "[id 25]Nuoc Hoa Calvin Klein Beauty Eau De Parfum For Her 100ml (1).jpg",
        img3: "[id 25]Nuoc Hoa Calvin Klein Beauty Eau De Parfum For Her 100ml (1).jpg",
        xuat_xu: "Mỹ, Pháp",
        nam_phat_hanh: "2010",
        nhom_huong: "Hoa nhài, Hạt vông vang, Gỗ virginia",
        phong_cach: "Cây vông vang",
        huong_dau: "Hoa Lê",
        huong_giua: "Hoa nhài",
        huong_cuoi: "Gỗ tuyết tùng Virginia"
    },

    {
        id: 26,
        name: "Prada La Femme Water Splash EDT 150ml",
        brand: "Prada",
        type: "Nữ",
        price: 1780000,
        img1: "[id 26]Nuoc Hoa Nu Prada La Femme Water Splash EDT 150ml (1).jpg",
        img2: "[id 26]Nuoc Hoa Nu Prada La Femme Water Splash EDT 150ml (2).jpg",
        img3: "[id 26]Nuoc Hoa Nu Prada La Femme Water Splash EDT 150ml (3).jpg",
        xuat_xu: "Pháp, Tây Ban Nha",
        nam_phat_hanh: "2021",
        nhom_huong: "Hoa chi đại, Green notes, Hoa mộc lan",
        phong_cach: "Tươi mới, Thanh lịch, Nữ tính",
        huong_dau: "Lá Quýt, Quả Quýt",
        huong_giua: "Hoa Sử, Mộc Lan, Lily of the Valley",
        huong_cuoi: "Gỗ Đàn Hương, Nốt Hương Xanh "
    },

    {
        id: 27,
        name: "Creed Himalaya EDP 100ml",
        brand: "Creed",
        type: "Nam",
        price: 4990000,
        img1: "[id 27]Nuoc Hoa Nam Creed Himalaya EDP 100ml (1).jpg",
        img2: "[id 27]Nuoc Hoa Nam Creed Himalaya EDP 100ml (2).jpg",
        img3: "[id 27]Nuoc Hoa Nam Creed Himalaya EDP 100ml (1).jpg",
        xuat_xu: "Pháp",
        nam_phat_hanh: "2002",
        nhom_huong: "Xạ hương, Gỗ đàn hương, Quả cam chanh",
        phong_cach: "Mạnh mẽ, Nam tính, Tinh tế",
        huong_dau: "Bưởi, Cam bergamot, Chanh vàng",
        huong_giua: "Đàn hương",
        huong_cuoi: "Xạ hương, Long diên hương, Tuyết tùng"
    },

    {
        id: 28,
        name: "Bvlgari Man Wood Essence 100ml",
        brand: "Bvlgari",
        type: "Nam",
        price: 1980000,
        img1: "[id 28]Nuoc Hoa Nam Bvlgari Man Wood Essence 100ml (1).jpg",
        img2: "[id 28]Nuoc Hoa Nam Bvlgari Man Wood Essence 100ml (2).jpg",
        img3: "[id 28]Nuoc Hoa Nam Bvlgari Man Wood Essence 100ml (3).jpg",
        xuat_xu: "Ý",
        nam_phat_hanh: "2018",
        nhom_huong: "Cây bách, An tức hương, Gỗ tuyết tùng",
        phong_cach: "Hấp dẫn, Tinh tế, Tự tin",
        huong_dau: "Cam quýt, Vỏ chanh, Rau mùi",
        huong_giua: "Tuyết tùng, Gỗ vetiver, Cây bách",
        huong_cuoi: "Hương benzoin"
    },

    {
        id: 29,
        name: "Polo Red Ralph Lauren EDT 125ml",
        brand: "Polo",
        type: "Nam",
        price: 1600000,
        img1: "[id 29]Nuoc Hoa Nam Polo Red Ralph Lauren EDT 125ml (1).jpg",
        img2: "[id 29]Nuoc Hoa Nam Polo Red Ralph Lauren EDT 125ml (2).jpg",
        img3: "[id 29]Nuoc Hoa Nam Polo Red Ralph Lauren EDT 125ml (3).jpg",
        xuat_xu: "Mỹ",
        nam_phat_hanh: "2003",
        nhom_huong: "Hương hoa cỏ An-Đê-Hít",
        phong_cach: "Hiện đại, quyến rũ, nam tính",
        huong_dau: "Quả bưởi, Quả chanh vàng Ý, Mạn việt quất",
        huong_giua: "Nghệ tây, Cây xô thơm",
        huong_cuoi: "Hương của gỗ, Hổ phách, Cà phê"
    },

    {
        id: 30,
        name: "Versace Eros Man EDT 100ml",
        brand: "Versace",
        type: "Nam",
        price: 1650000,
        img1: "[id 30]Nuoc Hoa Nam Versace Eros Man EDT 100ml (1).jpg",
        img2: "[id 30]Nuoc Hoa Nam Versace Eros Man EDT 100ml (2).jpg",
        img3: "[id 30]Nuoc Hoa Nam Versace Eros Man EDT 100ml (3).jpg",
        xuat_xu: "Ý",
        nam_phat_hanh: "2012",
        nhom_huong: "Vani, Bạc hà, Đậu tonka, Táo",
        phong_cach: "Nam tính, Gợi cảm, Thu hút",
        huong_dau: "Bạc hà, Táo xanh, Quả chanh vàng",
        huong_giua: "Đậu Tonka, Ambroxan, Geranium.",
        huong_cuoi: "Vanilla, Gỗ tuyết tùng, Cỏ hương bài, Rêu sồi"
    },
];

var userArray = [{
    id: 1,
    role: 1,
    email: "huuquocbao@gmail.com",
    name: "Hữu Quốc Bảo",
    password: "bao123456",
    sdt: "0123456781",
    yearborn: "2000",
    gt: "nam"
}, {
    id: 2,
    role: 0,
    email: "quocbao@gmail.com",
    name: "Quốc Bảo",
    password: "bao123456",
    sdt: "0123456781",
    yearborn: "2001",
    gt: "nữ"
}]

// End data

//Lưu data vào local storage
localStorage.setItem("products", JSON.stringify(productArray));

//Lưu data vào local storage
localStorage.setItem("user", JSON.stringify(userArray));